import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); if (!values.email || !values.password) return setError('Email and password are required.'); try { setSubmitting(true); await login(values.email, values.password); navigate('/dashboard'); } catch (e) { setError(e.response?.data?.message || 'Unable to sign in.'); } finally { setSubmitting(false); } };
  return <main className="grid min-h-screen place-items-center bg-gradient-to-br from-slate-950 to-sky-950 p-4"><form onSubmit={submit} className="w-full max-w-md space-y-5 rounded-2xl bg-white p-8 shadow-2xl"><div><p className="text-sm font-semibold uppercase tracking-widest text-sky-700">HMS · Phase 1</p><h1 className="mt-2 text-2xl font-bold text-slate-900">Hospital Administration</h1><p className="mt-1 text-sm text-slate-600">Sign in to continue securely.</p></div>{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="block text-sm font-medium">Email<input className="mt-1 w-full rounded-lg border p-2.5" name="email" type="email" autoComplete="email" required /></label><label className="block text-sm font-medium">Password<input className="mt-1 w-full rounded-lg border p-2.5" name="password" type="password" autoComplete="current-password" required /></label><button disabled={submitting} className="w-full rounded-lg bg-sky-700 py-2.5 font-medium text-white disabled:opacity-60">{submitting ? 'Signing in…' : 'Login'}</button></form></main>;
}
