import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); if (!values.email || !values.password) return setError('Email and password are required.'); try { setSubmitting(true); await login(values.email, values.password); navigate('/dashboard'); } catch (e) { setError(e.response?.data?.message || 'Unable to sign in.'); } finally { setSubmitting(false); } };
  return <main className="min-h-screen bg-[#f3f8f9] p-4 lg:grid lg:grid-cols-2 lg:p-6"><section className="relative hidden overflow-hidden rounded-3xl bg-slate-950 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full bg-teal-500/20 blur-3xl"/><div className="relative flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-teal-500 text-lg font-black">H</span><span><b className="block">HMS</b><small className="text-slate-400">Hospital Management System</small></span></div><div className="relative max-w-md"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-300">Healthcare operations</p><h1 className="mt-4 text-5xl font-bold leading-tight tracking-tight">Care, connected.</h1><p className="mt-5 text-lg leading-8 text-slate-300">A secure workspace for the people who keep hospital operations moving every day.</p></div><p className="relative text-sm text-slate-500">Secure hospital administration platform</p></section><section className="grid place-items-center"><form onSubmit={submit} className="w-full max-w-md space-y-6 rounded-2xl bg-white p-7 shadow-[0_14px_40px_rgba(15,23,42,0.08)] sm:p-9"><div className="lg:hidden"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal-700 font-black text-white">H</span></div><div><p className="text-sm font-semibold text-teal-700">Welcome back</p><h2 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Sign in to HMS</h2><p className="mt-2 text-sm text-slate-500">Enter your credentials to access your workspace.</p></div>{error && <p className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<label className="block text-sm font-semibold text-slate-700">Email address<input className="hms-input" name="email" type="email" autoComplete="email" placeholder="name@hospital.com" required /></label><label className="block text-sm font-semibold text-slate-700">Password<input className="hms-input" name="password" type="password" autoComplete="current-password" placeholder="Enter your password" required /></label><button disabled={submitting} className="hms-button-primary w-full py-3">{submitting ? 'Signing in…' : 'Sign in securely'}</button></form></section></main>;
}
