import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { doctorService } from '../services/doctor.service';
import { patientService } from '../services/patient.service';

const blank = { firstName: '', lastName: '', cnic: '', fatherName: '', phone: '', address: '', doctorId: '' };
const formatCnic = (value) => { const digits = value.replace(/\D/g, '').slice(0, 13); return [digits.slice(0, 5), digits.slice(5, 12), digits.slice(12)].filter(Boolean).join('-'); };
export function PatientRegistrationPage() {
  const navigate = useNavigate(); const [form, setForm] = useState(blank); const [doctors, setDoctors] = useState([]); const [errors, setErrors] = useState({}); const [error, setError] = useState(''); const [patient, setPatient] = useState(null); const [existing, setExisting] = useState(null); const [saving, setSaving] = useState(false);
  useEffect(() => { doctorService.list().then((r) => setDoctors(r.data.data.filter((doctor) => doctor.isActive))).catch(() => setError('Unable to load active doctors.')); }, []);
  const change = (event) => { const { name, value } = event.target; setForm((current) => ({ ...current, [name]: name === 'cnic' ? formatCnic(value) : value })); setErrors((current) => ({ ...current, [name]: '' })); };
  const validate = () => { const next = {}; [['firstName', 'First Name'], ['lastName', 'Last Name'], ['fatherName', 'Father Name'], ['phone', 'Phone Number'], ['address', 'Address']].forEach(([key, label]) => { if (!form[key].trim()) next[key] = `${label} is required.`; }); if (!form.cnic) next.cnic = 'CNIC Number is required.'; else if (!/^\d{5}-\d{7}-\d$/.test(form.cnic)) next.cnic = 'CNIC must use a valid Pakistani CNIC format.'; if (!form.doctorId) next.doctorId = 'Please select a doctor.'; setErrors(next); return !Object.keys(next).length; };
  const submit = async (event) => { event.preventDefault(); setError(''); setExisting(null); if (!validate()) return; setSaving(true); try { const found = await patientService.search({ cnic: form.cnic }); if (found.data.data.length) { setExisting(found.data.data[0]); return; } const response = await patientService.create({ first_name: form.firstName.trim(), last_name: form.lastName.trim(), cnic: form.cnic, father_name: form.fatherName.trim(), phone: form.phone.trim(), address: form.address.trim(), doctor_id: Number(form.doctorId) }); setPatient(response.data.data); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to register patient.'); } finally { setSaving(false); } };
  if (existing) return <div className="max-w-2xl rounded-xl bg-amber-50 p-6 shadow-sm ring-1 ring-amber-200"><h2 className="text-2xl font-bold text-amber-800">Patient Already Registered</h2><p className="mt-4"><b>Patient Number:</b> {existing.patientNumber}</p><p><b>Patient Name:</b> {existing.firstName} {existing.lastName}</p><p><b>Doctor:</b> Dr. {existing.doctor.firstName} {existing.doctor.lastName}</p><div className="mt-6 flex gap-3"><Link className="rounded bg-sky-700 px-4 py-2 text-white" to={`/patients/${existing.id}`}>View Patient</Link><button className="rounded border px-4 py-2" onClick={() => setExisting(null)}>Back to Form</button></div></div>;
  if (patient) return <div className="max-w-2xl rounded-xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-2xl font-bold text-emerald-700">Patient Registered Successfully</h2><dl className="mt-5 grid gap-3 sm:grid-cols-2">{[['Patient Number', patient.patientNumber], ['Patient Name', `${patient.firstName} ${patient.lastName}`], ['CNIC', patient.cnic], ['Father Name', patient.fatherName], ['Phone', patient.phone], ['Doctor', `Dr. ${patient.doctor.firstName} ${patient.doctor.lastName}`], ['Registration Date', new Date(patient.createdAt).toLocaleDateString()]].map(([label, value]) => <div key={label}><dt className="text-sm text-slate-500">{label}</dt><dd>{value}</dd></div>)}<div className="sm:col-span-2"><dt className="text-sm text-slate-500">Address</dt><dd>{patient.address}</dd></div></dl><div className="mt-6 flex flex-wrap gap-3"><Link className="rounded bg-sky-700 px-4 py-2 text-white" to={`/patients/${patient.id}`}>View Patient</Link><button className="rounded border px-4 py-2" onClick={() => window.print()}>Print Registration Slip</button><button className="rounded border px-4 py-2" onClick={() => { setPatient(null); setForm(blank); }}>Register Another Patient</button></div></div>;
  const fields = [['firstName', 'First Name', 'text', 'Enter first name'], ['lastName', 'Last Name', 'text', 'Enter last name'], ['cnic', 'CNIC Number', 'text', '35202-1234567-1'], ['fatherName', 'Father Name', 'text', 'Enter father name'], ['phone', 'Phone Number', 'tel', '03XX-XXXXXXX']];
  return <div className="max-w-3xl"><h2 className="text-2xl font-bold">Patient Registration</h2><p className="mt-1 text-slate-600">Register a new patient</p><form noValidate onSubmit={submit} className="mt-5 grid gap-4 rounded-xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:grid-cols-2">{error && <p className="rounded bg-red-50 p-3 text-red-700 sm:col-span-2">{error}</p>}{fields.map(([name, label, type, placeholder]) => <label className="text-sm font-medium" key={name}>{label}<input className={`mt-1 w-full rounded border p-2 ${errors[name] ? 'border-red-500' : ''}`} name={name} type={type} value={form[name]} onChange={change} placeholder={placeholder} />{errors[name] && <span className="mt-1 block text-xs text-red-700">{errors[name]}</span>}</label>)}<label className="text-sm font-medium">Under Which Doctor<select className={`mt-1 w-full rounded border p-2 ${errors.doctorId ? 'border-red-500' : ''}`} name="doctorId" value={form.doctorId} onChange={change}><option value="">Select Doctor</option>{doctors.map((doctor) => <option value={doctor.id} key={doctor.id}>Dr. {doctor.firstName} {doctor.lastName}{doctor.specialization ? ` — ${doctor.specialization}` : ''}</option>)}</select>{errors.doctorId && <span className="mt-1 block text-xs text-red-700">{errors.doctorId}</span>}</label><label className="text-sm font-medium sm:col-span-2">Address<textarea className={`mt-1 w-full rounded border p-2 ${errors.address ? 'border-red-500' : ''}`} name="address" value={form.address} onChange={change} placeholder="Enter complete address" rows="4" />{errors.address && <span className="mt-1 block text-xs text-red-700">{errors.address}</span>}</label><div className="flex justify-end gap-3 sm:col-span-2"><button type="button" className="rounded border px-4 py-2" onClick={() => navigate('/reception/patients')}>Cancel</button><button disabled={saving} className="rounded bg-sky-700 px-4 py-2 font-medium text-white disabled:opacity-60">{saving ? 'Registering…' : 'Register Patient'}</button></div></form></div>;
}
