import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { doctorService } from '../services/doctor.service';
import { patientService } from '../services/patient.service';

export function PatientDetailPage({ edit = false }) {
  const { id } = useParams(); const navigate = useNavigate(); const [patient, setPatient] = useState(null); const [doctors, setDoctors] = useState([]); const [form, setForm] = useState(null); const [error, setError] = useState('');
  useEffect(() => { patientService.get(id).then((response) => { setPatient(response.data.data); setForm({ ...response.data.data, doctorId: String(response.data.data.doctor.id) }); }).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load patient')); if (edit) doctorService.list().then((response) => setDoctors(response.data.data.filter((doctor) => doctor.isActive))); }, [id, edit]);
  if (error) return <p className="text-red-700">{error}</p>; if (!patient || !form) return <p>Loading patient…</p>;
  if (!edit) return <div className="max-w-2xl rounded-xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between"><h2 className="text-2xl font-bold">Patient Record</h2><Link className="text-sky-700" to="/reception/patients">Back</Link></div><dl className="mt-5 grid gap-4 sm:grid-cols-2">{[['Patient Number', patient.patientNumber], ['First Name', patient.firstName], ['Last Name', patient.lastName], ['CNIC Number', patient.cnic], ['Father Name', patient.fatherName], ['Phone Number', patient.phone], ['Under Which Doctor', `Dr. ${patient.doctor.firstName} ${patient.doctor.lastName}`], ['Registration Date', new Date(patient.createdAt).toLocaleString()], ['Registration Status', patient.registrationLocked ? 'Registration Locked' : 'Unlocked']].map(([label, value]) => <div key={label}><dt className="text-sm text-slate-500">{label}</dt><dd>{value}</dd></div>)}<div className="sm:col-span-2"><dt className="text-sm text-slate-500">Address</dt><dd>{patient.address}</dd></div></dl></div>;
  const save = async (event) => { event.preventDefault(); try { await patientService.update(id, { first_name: form.firstName, last_name: form.lastName, father_name: form.fatherName, cnic: form.cnic, phone: form.phone, address: form.address, doctor_id: Number(form.doctorId) }); navigate(`/patients/${id}`); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to update patient'); } };
  return <div className="max-w-2xl"><h2 className="mb-5 text-2xl font-bold">Edit Patient Registration</h2><form onSubmit={save} className="grid gap-4 rounded-xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:grid-cols-2">{error && <p className="text-red-700 sm:col-span-2">{error}</p>}{[['firstName', 'First Name'], ['lastName', 'Last Name'], ['fatherName', 'Father Name'], ['cnic', 'CNIC Number'], ['phone', 'Phone Number']].map(([key, label]) => <label key={key} className="text-sm font-medium">{label}<input className="mt-1 w-full rounded border p-2" value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })}/></label>)}<label className="sm:col-span-2 text-sm font-medium">Address<textarea className="mt-1 w-full rounded border p-2" value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })}/></label><label className="sm:col-span-2 text-sm font-medium">Under Which Doctor<select className="mt-1 w-full rounded border p-2" value={form.doctorId} onChange={(event) => setForm({ ...form, doctorId: event.target.value })}>{doctors.map((doctor) => <option key={doctor.id} value={doctor.id}>Dr. {doctor.firstName} {doctor.lastName}</option>)}</select></label><button className="rounded bg-sky-700 p-2 text-white sm:col-span-2">Save Changes</button></form></div>;
}
