import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { patientService } from '../services/patient.service';
import { useAuth } from '../context/AuthContext';

export function PatientListPage() {
  const { user } = useAuth(); const admin = user?.roles.includes('SUPER_ADMIN');
  const [data, setData] = useState({ items: [] }); const [search, setSearch] = useState(''); const [error, setError] = useState('');
  const load = async (term = '') => { try { setData((await patientService.list({ page: 1, limit: 20, search: term || undefined })).data.data); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load patients'); } };
  useEffect(() => { void load(); }, []);
  return <><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-bold">Patients</h2><div className="flex gap-2"><Link className="rounded bg-sky-700 px-4 py-2 text-white" to="/reception/patients/register">Register Patient</Link><Link className="rounded border px-4 py-2" to="/reception/patients/search">Search</Link></div></div><form className="mb-4 flex gap-2" onSubmit={(event) => { event.preventDefault(); void load(search); }}><input className="w-full max-w-lg rounded border p-2" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="CNIC, patient number, phone, or name"/><button className="rounded bg-slate-800 px-4 text-white">Search</button></form>{error && <p className="mb-3 text-red-700">{error}</p>}<div className="overflow-x-auto rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Patient Number</th><th>Patient Name</th><th>CNIC</th><th>Father Name</th><th>Phone</th><th>Doctor</th><th>Registration Date</th><th className="p-3">Action</th></tr></thead><tbody>{data.items.map((patient) => <tr className="border-t" key={patient.id}><td className="p-3 font-medium">{patient.patientNumber}</td><td>{patient.firstName} {patient.lastName}</td><td>{patient.cnic}</td><td>{patient.fatherName}</td><td>{patient.phone}</td><td>Dr. {patient.doctor.firstName} {patient.doctor.lastName}</td><td>{new Date(patient.createdAt).toLocaleDateString()}</td><td className="p-3"><Link className="text-sky-700" to={`/patients/${patient.id}`}>View</Link>{admin && <Link className="ml-3 text-sky-700" to={`/admin/patients/${patient.id}/edit`}>Edit</Link>}</td></tr>)}</tbody></table></div></>;
}
