import { database } from '../db/database.js';
import { AppError } from '../utils/app-error.js';

const select = `SELECT d.id, d.name, d.code, d.description, d.is_active AS isActive, d.created_at AS createdAt, d.updated_at AS updatedAt, d.created_by AS createdBy, COUNT(s.id) AS serviceCount FROM departments d LEFT JOIN services s ON s.department_id = d.id`;
const present = (row) => ({ ...row, isActive: Boolean(row.isActive), serviceCount: Number(row.serviceCount) });
const clauses = ({ search, status }) => { const conditions = []; const params = []; if (search) { conditions.push('(d.name LIKE ? OR d.code LIKE ?)'); params.push(`%${search}%`, `%${search}%`); } if (status === 'active') conditions.push('d.is_active = TRUE'); if (status === 'inactive') conditions.push('d.is_active = FALSE'); return { where: conditions.length ? ` WHERE ${conditions.join(' AND ')}` : '', params }; };

export const departmentService = {
  async list(query) { const { where, params } = clauses(query); const group = ' GROUP BY d.id, d.name, d.code, d.description, d.is_active, d.created_at, d.updated_at, d.created_by'; const offset = (query.page - 1) * query.limit; const [rows] = await database.execute(`${select}${where}${group} ORDER BY d.name LIMIT ${query.limit} OFFSET ${offset}`, params); const [counts] = await database.execute(`SELECT COUNT(*) AS total FROM departments d${where}`, params); const total = Number(counts[0].total); return { departments: rows.map(present), pagination: { page: query.page, limit: query.limit, total, totalPages: total ? Math.ceil(total / query.limit) : 0 } }; },
  async get(id) { const [rows] = await database.execute(`${select} WHERE d.id = ? GROUP BY d.id, d.name, d.code, d.description, d.is_active, d.created_at, d.updated_at, d.created_by`, [id]); if (!rows.length) throw new AppError(404, 'Department not found.'); return present(rows[0]); },
  async create(data, userId) { const [existing] = await database.execute('SELECT id FROM departments WHERE code = ?', [data.code]); if (existing.length) throw new AppError(409, 'Department code already exists.', [], 'code'); const [result] = await database.execute('INSERT INTO departments (name, code, description, created_by) VALUES (?, ?, ?, ?)', [data.name, data.code, data.description || null, userId]); return this.get(result.insertId); },
  async update(id, data) { const current = await this.get(id); if (data.code && data.code !== current.code) { const [existing] = await database.execute('SELECT id FROM departments WHERE code = ? AND id <> ?', [data.code, id]); if (existing.length) throw new AppError(409, 'Department code already exists.', [], 'code'); } const fields = { name: 'name', code: 'code', description: 'description' }; const changes = Object.entries(fields).filter(([key]) => key in data); await database.execute(`UPDATE departments SET ${changes.map(([, column]) => `${column} = ?`).join(', ')} WHERE id = ?`, [...changes.map(([key]) => data[key] || null), id]); return { old: current, department: await this.get(id) }; },
  async setStatus(id, isActive) { const current = await this.get(id); await database.execute('UPDATE departments SET is_active = ? WHERE id = ?', [isActive, id]); return { old: current, department: await this.get(id) }; },
};
