import { randomUUID } from "node:crypto";
import { database } from "../db/database.js";
import { AppError } from "../utils/app-error.js";
const patientSelect = `SELECT p.id, p.patient_number AS patientNumber, p.first_name AS firstName, p.last_name AS lastName, p.father_name AS fatherName, p.cnic, p.phone, p.address, p.is_active AS isActive, p.created_at AS createdAt, d.id AS doctorId, d.first_name AS doctorFirstName, d.last_name AS doctorLastName, d.specialization AS doctorSpecialization FROM patients p JOIN doctors d ON d.id = p.doctor_id`;
const presentPatient = (p) => ({ ...p, isActive: Boolean(p.isActive), doctor: { id: p.doctorId, firstName: p.doctorFirstName, lastName: p.doctorLastName, specialization: p.doctorSpecialization } });
const serviceSelect = `SELECT ps.id, ps.quantity, ps.unit_price AS unitPrice, ps.total_amount AS totalAmount, ps.notes, ps.status, ps.created_at AS createdAt, s.id AS serviceId, s.name AS serviceName, s.code AS serviceCode, d.name AS departmentName, u.first_name AS addedByFirstName, u.last_name AS addedByLastName FROM patient_services ps JOIN services s ON s.id = ps.service_id JOIN departments d ON d.id = s.department_id JOIN users u ON u.id = ps.added_by`;
const presentService = (row) => ({ ...row, unitPrice: Number(row.unitPrice), totalAmount: Number(row.totalAmount), addedBy: `${row.addedByFirstName} ${row.addedByLastName}` });
export const laboratoryService = {
  async search(query) { const filters=[]; const params=[]; for (const [field, column] of [["cnic","p.cnic"],["patientNumber","p.patient_number"],["phone","p.phone"]]) if (query[field]) { filters.push(`${column} LIKE ?`); params.push(`%${query[field]}%`); } if (query.search) { filters.push("(p.cnic LIKE ? OR p.patient_number LIKE ? OR p.phone LIKE ? OR CONCAT(p.first_name, ' ', p.last_name) LIKE ?)"); params.push(...Array(4).fill(`%${query.search}%`)); } if (!filters.length) return { items: [], page: query.page, limit: query.limit, total: 0, totalPages: 0 }; const where=` WHERE p.is_active = TRUE AND (${filters.join(" OR ")})`; const offset=(query.page-1)*query.limit; const [rows]=await database.execute(`${patientSelect}${where} ORDER BY p.created_at DESC LIMIT ${query.limit} OFFSET ${offset}`,params); const [count]=await database.execute(`SELECT COUNT(*) AS total FROM patients p${where}`,params); const total=Number(count[0].total); return { items: rows.map(presentPatient), page:query.page, limit:query.limit, total, totalPages:Math.ceil(total/query.limit) }; },
  async getPatient(id) { const [rows]=await database.execute(`${patientSelect} WHERE p.id = ? AND p.is_active = TRUE`,[id]); if (!rows.length) throw new AppError(404,"Patient not found."); const patient=presentPatient(rows[0]); const [history]=await database.execute(`${serviceSelect} WHERE ps.patient_id = ? AND d.code = 'LAB' ORDER BY ps.created_at DESC`,[id]); return { ...patient, laboratoryServices: history.map(presentService) }; },
  async availableServices() { const [rows]=await database.execute("SELECT s.id, s.name, s.code, s.description, s.price FROM services s JOIN departments d ON d.id = s.department_id WHERE d.code = 'LAB' AND s.is_active = TRUE AND d.is_active = TRUE ORDER BY s.name"); return rows.map((row)=>({ ...row, price:Number(row.price) })); },
  async addService(patientId, input, actorId) { const connection=await database.getConnection(); try { await connection.beginTransaction(); const [patients]=await connection.execute("SELECT id FROM patients WHERE id = ? AND is_active = TRUE FOR UPDATE",[patientId]); if (!patients.length) throw new AppError(404,"Patient not found."); const [services]=await connection.execute("SELECT s.id, s.price, s.is_active AS isActive, d.code AS departmentCode FROM services s JOIN departments d ON d.id=s.department_id WHERE s.id = ? FOR UPDATE",[input.serviceId]); if (!services.length) throw new AppError(404,"Laboratory service not found."); const service=services[0]; if (service.departmentCode !== "LAB") throw new AppError(400,"Selected service is not a laboratory service."); if (!service.isActive) throw new AppError(400,"This laboratory service is currently inactive."); if (!Number.isInteger(input.quantity)||input.quantity<1) throw new AppError(400,"Quantity must be a positive whole number."); const unitPrice=Number(service.price); const totalAmount=unitPrice*input.quantity; const [result]=await connection.execute("INSERT INTO patient_services (patient_id, service_id, quantity, unit_price, total_amount, notes, added_by) VALUES (?, ?, ?, ?, ?, ?, ?)",[patientId,input.serviceId,input.quantity,unitPrice,totalAmount,input.notes||null,actorId]); await connection.execute("INSERT INTO audit_logs (id, user_id, action, entity, entity_id, new_data) VALUES (?, ?, 'LAB_SERVICE_ADDED', 'PATIENT_SERVICE', ?, ?)",[randomUUID(),actorId,String(result.insertId),JSON.stringify({patientId,serviceId:input.serviceId,quantity:input.quantity,unitPrice,totalAmount})]); await connection.commit(); return { id:result.insertId, patientId:Number(patientId), serviceId:input.serviceId, quantity:input.quantity, unitPrice, totalAmount, status:"ADDED", notes:input.notes||null }; } catch (error) { await connection.rollback(); throw error; } finally { connection.release(); } },
};
