import { database } from '../db/database.js';
import { AppError } from '../utils/app-error.js';

const select = `SELECT rp.id, rp.receipt_number AS receiptNumber, rp.amount, rp.payment_method AS paymentMethod, rp.payment_status AS paymentStatus, rp.paid_at AS paidAt, rp.created_at AS createdAt, p.id AS patientId, p.patient_number AS patientNumber, p.first_name AS firstName, p.last_name AS lastName, p.cnic, p.father_name AS fatherName, CONCAT('Dr. ', d.first_name, ' ', d.last_name) AS doctorName, u.id AS receivedById, u.first_name AS receivedByFirstName, u.last_name AS receivedByLastName FROM registration_payments rp JOIN patients p ON p.id = rp.patient_id JOIN doctors d ON d.id = p.doctor_id JOIN users u ON u.id = rp.received_by`;
const present = (row) => ({ id: row.id, receiptNumber: row.receiptNumber, amount: Number(row.amount), paymentMethod: row.paymentMethod, paymentStatus: row.paymentStatus, paidAt: row.paidAt, createdAt: row.createdAt, patient: { id: row.patientId, patientNumber: row.patientNumber, firstName: row.firstName, lastName: row.lastName, cnic: row.cnic, fatherName: row.fatherName, doctorName: row.doctorName }, receivedBy: { id: row.receivedById, firstName: row.receivedByFirstName, lastName: row.receivedByLastName } });

export const registrationPaymentService = {
  async list({ page, limit, search, from, to }) { const offset = (page - 1) * limit; const terms = []; const params = []; if (search) { terms.push('(p.patient_number LIKE ? OR rp.receipt_number LIKE ? OR p.cnic LIKE ?)'); params.push(`%${search}%`, `%${search}%`, `%${search}%`); } if (from) { terms.push('DATE(rp.paid_at) >= ?'); params.push(from); } if (to) { terms.push('DATE(rp.paid_at) <= ?'); params.push(to); } const where = terms.length ? ` WHERE ${terms.join(' AND ')}` : ''; const [rows] = await database.execute(`${select}${where} ORDER BY rp.paid_at DESC LIMIT ? OFFSET ?`, [...params, limit, offset]); const [counts] = await database.execute(`SELECT COUNT(*) AS total FROM registration_payments rp JOIN patients p ON p.id = rp.patient_id${where}`, params); return { items: rows.map(present), page, limit, total: counts[0].total }; },
  async get(id) { const [rows] = await database.execute(`${select} WHERE rp.id = ?`, [id]); if (!rows.length) throw new AppError(404, 'Registration payment not found'); return present(rows[0]); },
};
