import { database } from '../db/database.js';
import { AppError } from '../utils/app-error.js';

const select = `SELECT s.id, s.name, s.code, s.description, s.price, s.is_active AS isActive, s.created_at AS createdAt, s.updated_at AS updatedAt, s.created_by AS createdBy, d.id AS departmentId, d.name AS departmentName, d.code AS departmentCode FROM services s JOIN departments d ON d.id = s.department_id`;
const present = (row) => ({ id: row.id, name: row.name, code: row.code, description: row.description, price: Number(row.price), isActive: Boolean(row.isActive), createdAt: row.createdAt, updatedAt: row.updatedAt, createdBy: row.createdBy, department: { id: row.departmentId, name: row.departmentName, code: row.departmentCode } });
const filters = ({ search, status, departmentId }) => { const conditions = []; const params = []; if (departmentId) { conditions.push('s.department_id = ?'); params.push(departmentId); } if (search) { conditions.push('(s.name LIKE ? OR s.code LIKE ? OR s.description LIKE ?)'); params.push(`%${search}%`, `%${search}%`, `%${search}%`); } if (status === 'active') conditions.push('s.is_active = TRUE'); if (status === 'inactive') conditions.push('s.is_active = FALSE'); return { where: conditions.length ? ` WHERE ${conditions.join(' AND ')}` : '', params }; };
export const serviceService = {
  async list(query) { const { where, params } = filters(query); const offset = (query.page - 1) * query.limit; const [rows] = await database.execute(`${select}${where} ORDER BY s.name LIMIT ${query.limit} OFFSET ${offset}`, params); const [counts] = await database.execute(`SELECT COUNT(*) AS total FROM services s${where}`, params); const total = Number(counts[0].total); return { services: rows.map(present), pagination: { page: query.page, limit: query.limit, total, totalPages: total ? Math.ceil(total / query.limit) : 0 } }; },
  async get(id) { const [rows] = await database.execute(`${select} WHERE s.id = ?`, [id]); if (!rows.length) throw new AppError(404, 'Service not found.'); return present(rows[0]); },
  async validateDepartment(departmentId) { const [rows] = await database.execute('SELECT id, is_active AS isActive FROM departments WHERE id = ?', [departmentId]); if (!rows.length) throw new AppError(400, 'Selected department does not exist.', [], 'departmentId'); if (!rows[0].isActive) throw new AppError(400, 'Cannot assign a service to an inactive department.', [], 'departmentId'); },
  async create(data, userId) { if (data.price < 0) throw new AppError(400, 'Service price must be zero or greater.', [], 'price'); await this.validateDepartment(data.departmentId); const [existing] = await database.execute('SELECT id FROM services WHERE code = ?', [data.code]); if (existing.length) throw new AppError(409, 'Service code already exists.', [], 'code'); const [result] = await database.execute('INSERT INTO services (department_id, name, code, description, price, created_by) VALUES (?, ?, ?, ?, ?, ?)', [data.departmentId, data.name, data.code, data.description || null, data.price, userId]); return this.get(result.insertId); },
  async update(id, data) { const current = await this.get(id); if (data.price !== undefined && data.price < 0) throw new AppError(400, 'Service price must be zero or greater.', [], 'price'); if (data.departmentId && data.departmentId !== current.department.id) await this.validateDepartment(data.departmentId); if (data.code && data.code !== current.code) { const [existing] = await database.execute('SELECT id FROM services WHERE code = ? AND id <> ?', [data.code, id]); if (existing.length) throw new AppError(409, 'Service code already exists.', [], 'code'); } const fields = { departmentId: 'department_id', name: 'name', code: 'code', description: 'description', price: 'price' }; const changes = Object.entries(fields).filter(([key]) => key in data); await database.execute(`UPDATE services SET ${changes.map(([, column]) => `${column} = ?`).join(', ')} WHERE id = ?`, [...changes.map(([key]) => data[key] ?? null), id]); return { old: current, service: await this.get(id) }; },
  async setStatus(id, isActive) { const current = await this.get(id); await database.execute('UPDATE services SET is_active = ? WHERE id = ?', [isActive, id]); return { old: current, service: await this.get(id) }; },
};
